### ISSUE TITLE
Use pipeline without root privelages

### ISSUE THREAD

**Issue by timghaly** [EBI-Metagenomics/mobilome-annotation-pipeline#20]
This seems like a great pipeline, however, as far as I am aware Singularity cannot be installed without root privileges. Is it possible to run this pipeline without needing to install singularity?

Thanks

**Comment by mberacochea** [comment]
Hi @timghaly

The requirement to have singularity intalled is to because ICEfinder requires users to request for a copy of it. We included the instructions on how to build the container for singularity, which is the most common container tech in HPC clusters. Are you trying to run the pipeline in your laptop or in a cluster?

We could support Docker as the container engine, that would require us to convert https://github.com/EBI-Metagenomics/mobilome-annotation-pipeline/blob/main/templates/icefinder-v1.0-local.def as a Dockerfile.

Cheers

**Comment by timghaly** [comment]
Thanks for you response.
My apologies, I mistakingly believed that Singularity was not available on the HPC cluster that I have access to. It turns out that it does. I should be fine to get the pipeline up and running.
Thanks you for your help.
Cheers
